substitutions:
  device: vindriktning
  name: VINDRIKTNING

esphome:
  name: ${device}
  platform: ESP8266
  board: esp12e

<<: !include common/common.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi-info.yaml

switch:
  - !include common/switch/restart.yaml

uart:
  rx_pin: GPIO5
  baud_rate: 9600

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: pm1006
    pm_2_5:
      id: pm2_5
      name: PM2.5
      filters:
        - sliding_window_moving_average:
            window_size: 7
            send_every: 7
            send_first_at: 7
